spring:
  cloud:
    gateway:
      routes:
      - id: libray_route
        uri: http://localhost:8082
        predicates:
        - Path=/library/**
        metadata:
          response-timeout: 3000
          connect-timeout: 3000
      globalcors:
        cors-configurations:
           '[/**]':
            allowedOrigins: 
            - "http://localhost:3000"
            allowedMethods:
            - "*"
            allowedHeaders:
            - "*"
        add-to-simple-url-handler-mapping: true
          

server:
  port: 8083
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

